### ISSUE TITLE
Inspecting the wallet of another participant shows my own wallet

### ISSUE THREAD

**Issue by skuro** [d-cent/freecoin#7]
Regardless of the `:uid` URI parameter, going to:

    http://freecoin/participant/<:uid>

always shows my wallet

**Comment by skuro** [comment]
@jaromil might be the late hour, but I'm unsure whether it's best to follow the approach of 4185206 or 365fc87. 

Main difference is that the latter changes `auth/has-wallet` so that if there's an `:uid` parameter in the context, then that one is always used to fetch the wallet, which might be crossing the `auth` scope. 
Instead, in 4185206 it's the liberator resource to manage the logic of choosing which `:uid` to use for fetching the wallet, which seems a bit cleaner albeit more verbose.

I'll give it a better thought tomorrow, if you have any brain cycle to spare I'd love to hear your thoughts.

**Comment by jaromil** [comment]
had a look in the morning,  4185206 seems better to me. I did try before the more minimal intervention but it does impact the auth model.

**Comment by skuro** [comment]
good then, I'll revert & close the issue
